### ISSUE TITLE
what is the '*.lab.gz' file?

### ISSUE THREAD

**Issue by gogyzzz** [Jamiroquai88/VBDiarization#16]
I have AMI Headset wavs, but *.lab.gz is not.

I thought the *.lab.gz file is vad binary archive file of kaldi(from compute-vad), but it seems not.

How can I get the *.lab.gz files?

Thanks.

**Comment by gogyzzz** [comment]
I found what the *.lab.gz is.

```
cat tmp.vad.lab
# 1 0 0 1 1
```

```python
import numpy as np
np.loadtxt('tmp.vad.lab', dtype=object)
# array(['1', '0', '0', '1', '1'], dtype=object)
```

**Comment by shuvam-creditmate** [comment]
Hi. I assumed that the VAD would be automated. Any updates on this?

**Comment by Jamiroquai88** [comment]
@gogyzzz please look at examples, lab.gz si basically [start] [end] segmentation
@shuvam-creditmate you are welcomed to add this functionality, maybe just create wrapper in kaldi

**Comment by gogyzzz** [comment]
> Hi. I assumed that the VAD would be automated. Any updates on this?

Yes. the *.lab.gz has VAD information, but I wonder what VAD for making it.

It is from htk? *.lab is htk format.

**Comment by gogyzzz** [comment]
@shuvam-creditmate Thanks, I created rttm and segment file using some script. It seems to work.

**Comment by tylercollins590** [comment]
@gogyzzz did you end up finding/creating a script to generate the VAD files?

**Comment by shuvam-creditmate** [comment]
@tylercollins590 You can create a simple python script using [https://www.idiap.ch/software/bob/docs/bob/bob.kaldi/master/index.html#](this). The documentation is well done and it won't take much time to implement.
