### ISSUE TITLE
hi  ,is this code the source code of the  Bayesian HMM based x-vector clustering for Speaker Diarization? 

### ISSUE THREAD

**Issue by BLack-yzf** [Jamiroquai88/VBDiarization#19]
this is the article :http://www.fit.vutbr.cz/research/pubs/index.php?id=12085

**Comment by Jamiroquai88** [comment]
bo

**Comment by BLack-yzf** [comment]
thank you.And what is the clustering algorithm you used in the code ?  the VB diarization?

**Comment by Jamiroquai88** [comment]
AHC/K-means I think. For details, see https://github.com/Jamiroquai88/VBDiarization/blob/master/vbdiar/scoring/diarization.py

**Comment by BLack-yzf** [comment]
okay,thanks very much.
