### ISSUE TITLE
ONNX dim error

### ISSUE THREAD

**Issue by xianch55** [Jamiroquai88/VBDiarization#21]
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: 0 for the following indices
index: 2 Got: 56 Expected: 100

I have a problem with onnx and input feature dimensionality. When my input features are not [100,23]. It doesn't matter if features 0. dimension is longer or shorter. The problem is in both situations. How can I correct it?

**Comment by Jamiroquai88** [comment]
Hi, what is your version of `onnxruntime`? Try to downgrade to `onnxruntime==0.3.0` and let me know, if it works for you. I will add version specification into `requirements.txt`.

**Comment by Jamiroquai88** [comment]
closed due to inactivity
