### ISSUE TITLE
Overlapping Speeches

### ISSUE THREAD

**Issue by sajal-dei** [Jamiroquai88/VBDiarization#24]
Hey, I wanted to know, if this diarization covers overlapping speeches too?

**Comment by Jamiroquai88** [comment]
no

**Comment by anuar96** [comment]
if args.mode == 'diarization':
        if args.in_rttm_dir:
            diar.evaluate(scores=result, in_rttm_dir=args.in_rttm_dir, collar_size=0.25, evaluate_overlaps=False)
