### ISSUE TITLE
Hardcoded KALDI_ROOT_PATH leads to installation problems

### ISSUE THREAD

**Issue by vadimkantorov** [Jamiroquai88/VBDiarization#29]
https://github.com/Jamiroquai88/VBDiarization/blob/master/vbdiar/kaldi/__init__.py#L11 sets `KALDI_ROOT_PATH = '/Users/profant/kaldi'` and thus fails `python setup.py install`

**Comment by Jamiroquai88** [comment]
See https://github.com/Jamiroquai88/VBDiarization#installation

**Comment by vadimkantorov** [comment]
Thanks! Sorry for not checking the docs properly :( On a practical note, a suggestion can be to replace this line with: `KALDI_ROOT_PATH = os.getenv('KALDI_ROOT_PATH', 'some default value')`

**Comment by Jamiroquai88** [comment]
fixed, thanks for the suggestion
