### ISSUE TITLE
VBdiarization

### ISSUE THREAD

**Issue by czecze123** [Jamiroquai88/VBDiarization#32]
1. I want to ask the logic problem of speech segmentation. After the environment is set up, the program will run `onnxruntime.capi.onnxruntime_ pybind11_ state.InvalidArgument : [ONNXRuntimeError] : 2 index: 2 Got: 121 Expected: 100 Please fix either the inputs or the model.`
Where there is an error and how to correct it? 

2. The input voice signals list_ spk.scp In file Fe_ 03_ 00001-a 1 fe_ 03_ 00001-b 1 has only one person, why do we need to implement speaker segmentation?
Thank you!
By the way , i cannot contact you by e-mail.

**Comment by Jamiroquai88** [comment]
Hi,

1. Please try `pip install onnxruntime==0.3.0` as specified in `requirements.txt`
2. Yeah, it is just some prehistoric example. I will probably substitute it with something different in the future.

**Comment by czecze123** [comment]
Could you please tell me the version in the `requirements.txt` in your system?
scipy
scikit-learn
numpy
pyyaml
onnxruntime
spherecluster
pyclustering
kaldiio
Thank you!



At 2020-09-25 13:52:09, "Jan Profant" <notifications@github.com> wrote:

Hi,

Please try pip install onnxruntime==0.3.0 as specified in requirements.txt
Yeah, it is just some prehistoric example. I will probably substitute it with something different in the future.

**Comment by Jamiroquai88** [comment]
sorry about that, I made some mistake in merging or something, please check `requirements.txt` now

**Comment by czecze123** [comment]
> sorry about that, I made some mistake in merging or something, please check `requirements.txt` now

thanks!
