### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by usmanzafar12** [Jamiroquai88/VBDiarization#6]
Hello, can you share the parameters you used to get the results on the AMI corpus?. I am unable to get the same results using the same code and pre-trained ubm models from voice biometry

**Comment by Jamiroquai88** [comment]
Hi, models can be problematic - it is difficult to say, that models are fully compatible - GMM, T matrix, ...

current master is now fully compatible with x-vectors, code was completely rewritten - tested on linux and macOS
