### ISSUE TITLE
error: [Error 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by adarsh123456789** [Jamiroquai88/VBDiarization#9]
![err2](https://user-images.githubusercontent.com/24991855/59825206-065e7b00-9351-11e9-9d3b-96491f839ee7.PNG)
I was getting this error while I was using python3.7, now using python2.7 and getting the same error. I have tried few solutions but none of them seems to work.
I have tried out almost every solution listed in the below link;
https://github.com/jupyter/notebook/issues/4079

I have made changes to few things in the file setup.py, like I have added the extension .cc after 'nnet3-copy' and 'copy-matrix'

_nnet_copy_binary = os.path.join(KALDI_ROOT_PATH, 'src', 'nnet3bin', '**nnet3-copy.cc**')
    if not os.path.isfile(nnet_copy_binary):
        raise ValueError('nnet3-copy binary not found in `{}`.'.format(os.path.dirname(nnet_copy_binary)))
    copy_matrix_binary = os.path.join(KALDI_ROOT_PATH, 'src', 'bin', '**copy-matrix.cc**')
    if not os.path.isfile(copy_matrix_binary):
        raise ValueError('copy-matrix binary not found in `{}`.'.format(os.path.dirname(copy_matrix_binary)))_

I'm attaching the modified setup.py file in .txt format for better reference.
[setup.txt](https://github.com/Jamiroquai88/VBDiarization/files/3309051/setup.txt)

**Comment by Jamiroquai88** [comment]
Hi,

do you have `Kaldi` installed? Try to use new master, I just meged it.

**Comment by adarsh123456789** [comment]
Yeah I had Kaldi installed in the 1st place. thanks, the new master code worked for the setup.

As of now I'm facing a different issue, i.e.
![errr](https://user-images.githubusercontent.com/24991855/59840235-927f9b00-936f-11e9-968d-09116abeb134.PNG)

onnxruntime was not being identified as a module so I tried installing onnx which again raises an issue

**Comment by Jamiroquai88** [comment]
`pip install onnxruntime` worked?

**Comment by adarsh123456789** [comment]
![errr2](https://user-images.githubusercontent.com/24991855/59840743-98c24700-9370-11e9-85cb-e7020a305db7.PNG)
no it doesn't !

**Comment by Jamiroquai88** [comment]
you are probably running python2.7, try with python3.6

**Comment by adarsh123456789** [comment]
For the time being, I am trying the onnx installation using conda:
conda install -c conda-forge onnx

if this still doesn't work then I will try with python 3.6

**Comment by adarsh123456789** [comment]
As of now I'm using python 3.7.1
And I'm facing the below error when I'm trying to run the examples/diarization.py 
![OSerror](https://user-images.githubusercontent.com/24991855/59847752-01b1bb00-9381-11e9-83d5-6b5b9c65d456.PNG)

and here is the potential line 73
![OSerror2](https://user-images.githubusercontent.com/24991855/59847780-1aba6c00-9381-11e9-84d4-5463449fbca1.PNG)

a solution on the internet suggests something like below, which I'm having a hard time understanding:
https://stackoverflow.com/questions/25651990/oserror-winerror-193-1-is-not-a-valid-win32-application

**Comment by adarsh123456789** [comment]
Having the above error when trying in python 3.6 too.
the command i"m using to run the examples/diarization.py is given below:

`python examples/diarization.py -l examples/lists/AMI_dev-eval.scp -c configs/vbdiar.yml -m diarization --audio-dir wav/AMI/IHM_SUM --vad-dir vad/AMI --out-emb-dir emb/AMI/IHM_SUM --in-rttm-dir rttms/AMI`
 I'm doubtful, maybe I'm missing something really very silly while running the above.

**Comment by Jamiroquai88** [comment]
First of all, the command used above assumes, that you have AMI database downloaded and in the correct format - unfortunately, I am not able to redistribute this database.
A good start would be to run example audios in `example/` folder - there are wave files and VAD.

**Comment by Jamiroquai88** [comment]
Closed due to inactivity.
